Repository dbeattie/nag-me, pull requests merged in 2020-02, with the labels that each got.

#32 add basic react routes with components folder
  src/App.js
  src/components/appbar.js
  src/components/button.js
  src/components/creategoals.js
  src/components/goalsIndex.js
  src/components/login.js
  src/components/nagtracker.js
  src/components/register.js
Labels: feature

#34 add button
  src/components/button.js
Labels: feature

#37 add basic goal page
  src/App.js
  src/components/GoalsIndex.js
  src/components/goalsIndex.js
Labels: feature

#49 add button to the create goal page
  src/components/Button.js
  src/components/Login.js
  src/components/Nagtracker.js
  src/components/Register.js
Labels: feature

#62 Install material table
  package-lock.json
  package.json
  src/App.js
  src/components/GoalsIndex.js
  src/components/Register.js
Labels: feature

#65 sending json to db for register
  package-lock.json
  package.json
  src/components/Login.js
  src/components/Register.js
Labels: feature

#66 fixed login/register pages
  package.json
  src/components/Login.js
  src/components/Register.js
Labels: design fix

#67 add withCredentials object to fetch cookies from back end
  src/components/Login.js
  src/components/Register.js
Labels: feature

#73 on logout click, clear cookies
  src/components/Login.js
  src/components/NavBar.js
Labels: feature

#79 create nav bar slider with menu options
  src/components/NavBar.js
Labels: feature

#81 fix floating button location/onClick
  src/App.js
  src/components/CreateNewFloatingButton.js
  src/components/FloatingButtonToCreateNew.js
  src/components/GoalsIndex.js
  src/components/NagTracker.js
Labels: design fix

#90 Set navbar auth
  src/App.js
  src/components/GoalsIndex.js
  src/components/Login.js
  src/components/NagTracker.js
  src/components/NavBar.js
  src/components/Register.js
  src/helpers/AuthContext.js
  src/helpers/CheckAuth.js
  src/helpers/PrivateRoute.js
Labels: feature

#91 basic card setup for goals
  src/components/Card.js
  src/components/GoalsIndex.js
Labels: feature

#93 added floating button back into goals page
  src/App.js
  src/components/Card.js
  src/components/GoalsIndex.js
Labels: design fix

#94 got user id into state on authentication
  src/App.js
  src/components/Card.js
  src/components/CreateGoalsForm.js
  src/components/GoalsIndex.js
  src/components/Login.js
  src/components/NagTracker.js
  src/components/NavBar.js
  src/components/Register.js
Labels: feature

#100 cleaned up the card logic and delete function
  src/components/GoalsIndex.js
Labels: design fix

#104 add nagcard page
  src/components/GoalCard.js
  src/components/GoalsIndex.js
  src/components/NagCard.js
  src/components/NagTracker.js
Labels: feature

#105 add user context hook for user specific content
  src/App.js
  src/components/CreateGoalsForm.js
  src/components/GoalsIndex.js
  src/components/NagTracker.js
  src/components/Picker.js
  src/helpers/AuthContext.js
  src/helpers/CheckAuth.js
  src/helpers/PrivateRoute.js
  src/helpers/UserContext.js
Labels: feature

#106 update nag query to get specific users goal nags
  src/components/NagTracker.js
Labels: feature

#107 handle toggle yes and no on nags, plus clean up of goalcard.js
  src/components/GoalCard.js
  src/components/NagCard.js
  src/components/NagTracker.js
Labels: feature

#112 fixed axios response to filter properly
  src/App.js
  src/components/CreateGoalsForm.js
  src/components/GoalsIndex.js
  src/components/Login.js
  src/components/NagTracker.js
Labels: bug

#113 fixed a syntax error
  src/App.js
  src/components/GoalsIndex.js
Labels: bug

#115 fix goals only belonging to the user to show
  src/components/GoalsIndex.js
Labels: bug

#117 fixed authentication requests
  src/components/GoalsIndex.js
  src/components/Register.js
Labels: bug

#123 Fix all queries
  src/App.js
  src/components/CreateGoalsForm.js
  src/components/GoalsIndex.js
  src/components/Login.js
  src/components/NagTracker.js
  src/components/Register.js
Labels: design fix

#121 Fixed the redirection issue after user submit a new goal
  src/components/CreateGoalsForm.js
  src/components/EditGoalsForm.js
  src/components/GoalsIndex.js
Labels: design fix

#120 Add chart
  package-lock.json
  package.json
  src/App.js
  src/components/Chart.js
  src/components/Login.js
  src/components/NagTracker.js
Labels: feature

#124 fixed some compiling errors
  src/components/GoalsIndex.js
Labels: bug

#127 Update dynamic chart
  src/components/Chart.js
  src/components/NagCard.js
  src/components/NagTracker.js
  src/components/Picker.js
Labels: feature

#128 create context for goals associated with user
  src/App.js
  src/components/EditGoalsForm.js
  src/components/GoalCard.js
  src/components/GoalsIndex.js
  src/components/Picker.js
  src/helpers/GoalsContext.js
Labels: design fix

#129 matched up back end nomenclature with front end
  src/components/EditGoalsForm.js
  src/components/Picker.js
Labels: bug

#130 update colours
  src/components/Chart.js
Labels: design fix

#131 fixed nag date rendering to human view
  src/components/NagCard.js
  src/components/NagTracker.js
Labels: bug

#133 update colour to chart
  src/components/Chart.js
Labels: design fix

#135 fixed title spacing & add color/icons to yes/no buttons
  src/components/GoalsIndex.js
  src/components/NagCard.js
  src/components/NagTracker.js
Labels: design fix

#137 change styles to match chart color with yes/no buttons
  src/components/Chart.js
  src/components/CreateNewFloatingButton.js
Labels: design fix

#136 code clean up and copyright helper made
  README.md
  src/components/Button.js
  src/components/Chart.js
  src/components/CreateGoalsForm.js
  src/components/CreateNewFloatingButton.js
  src/components/EditGoalsForm.js
  src/components/Login.js
  src/components/NagCard.js
  src/components/NagTracker.js
  src/components/NavBar.js
  src/components/Picker.js
  src/components/Register.js
  src/components/Video.js
  src/helpers/CopyRight.js
Labels: design fix

#138 fix duplicate chart data
  src/components/Chart.js
Labels: bug

#139 updated some words on chart and cards
  src/components/Chart.js
  src/components/GoalCard.js
  src/components/NagCard.js
Labels: design fix

#140 fix edit form so existing nag renders too
  src/components/EditGoalsForm.js
  src/components/GoalsIndex.js
Labels: bug, design fix

#141 Update README.md
  README.md
Labels: design fix

#142 added a couple of screenshots for the README
  docs/GoalPage.png
  docs/NagTrackerChart.png
Labels: documentation

#143 added screenshots to readme directly
  README.md
Labels: documentation
